[package]
name = "xtask"
version = "3.1.1"
authors = ["Anza Maintainers <maintainers@anza.xyz>"]
description = "Blockchain, Rebuilt for Scale"
repository = "https://github.com/anza-xyz/agave"
homepage = "https://anza.xyz/"
license = "Apache-2.0"
edition = "2021"
publish = false

[features]
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.31", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.28"
tokio = { version = "1.48.0", features = ["full"] }
